//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omni.E10Solutions.Cam.JobApp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\ANAJ")]
        public string AnaSourceDirectory {
            get {
                return ((string)(this["AnaSourceDirectory"]));
            }
            set {
                this["AnaSourceDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\ANAJ\\Archive")]
        public string AnaArchivesDirectory {
            get {
                return ((string)(this["AnaArchivesDirectory"]));
            }
            set {
                this["AnaArchivesDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\ANAJ\\Invalid")]
        public string AnaErrorDirectory {
            get {
                return ((string)(this["AnaErrorDirectory"]));
            }
            set {
                this["AnaErrorDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\ANAJ\\InProcess")]
        public string AnaInProcessDirectory {
            get {
                return ((string)(this["AnaInProcessDirectory"]));
            }
            set {
                this["AnaInProcessDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\DUCJ")]
        public string DucSourceDirectory {
            get {
                return ((string)(this["DucSourceDirectory"]));
            }
            set {
                this["DucSourceDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\DUCJ\\Archive")]
        public string DucArchivesDirectory {
            get {
                return ((string)(this["DucArchivesDirectory"]));
            }
            set {
                this["DucArchivesDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\DUCJ\\Invalid")]
        public string DucErrorDirectory {
            get {
                return ((string)(this["DucErrorDirectory"]));
            }
            set {
                this["DucErrorDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\DUCJ\\InProcess")]
        public string DucInProcessDirectory {
            get {
                return ((string)(this["DucInProcessDirectory"]));
            }
            set {
                this["DucInProcessDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\EVEJ")]
        public string EveSourceDirectory {
            get {
                return ((string)(this["EveSourceDirectory"]));
            }
            set {
                this["EveSourceDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\EVEJ\\Archive")]
        public string EveArchivesDirectory {
            get {
                return ((string)(this["EveArchivesDirectory"]));
            }
            set {
                this["EveArchivesDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\EVEJ\\Invalid")]
        public string EveErrorDirectory {
            get {
                return ((string)(this["EveErrorDirectory"]));
            }
            set {
                this["EveErrorDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\EVEJ\\InProcess")]
        public string EveInProcessDirectory {
            get {
                return ((string)(this["EveInProcessDirectory"]));
            }
            set {
                this["EveInProcessDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\SACJ")]
        public string SacSourceDirectory {
            get {
                return ((string)(this["SacSourceDirectory"]));
            }
            set {
                this["SacSourceDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\SACJ\\Archive")]
        public string SacArchivesDirectory {
            get {
                return ((string)(this["SacArchivesDirectory"]));
            }
            set {
                this["SacArchivesDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\SACJ\\Invalid")]
        public string SacErrorDirectory {
            get {
                return ((string)(this["SacErrorDirectory"]));
            }
            set {
                this["SacErrorDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\SACJ\\InProcess")]
        public string SacInProcessDirectory {
            get {
                return ((string)(this["SacInProcessDirectory"]));
            }
            set {
                this["SacInProcessDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("net.tcp://OMSVEPIAZU902/E10Pilot")]
        public string AppServerUrl {
            get {
                return ((string)(this["AppServerUrl"]));
            }
            set {
                this["AppServerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\")]
        public string LoadPath {
            get {
                return ((string)(this["LoadPath"]));
            }
            set {
                this["LoadPath"] = value;
            }
        }
    }
}
