//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omni.E10Solutions.Cam.QuoteApp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\ROLLUP-PILOT\\ANAQ")]
        public string AnaSourceDirectory {
            get {
                return ((string)(this["AnaSourceDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\ROLLUP-PILOT\\ANAQ\\Archive")]
        public string AnaArchivesDirectory {
            get {
                return ((string)(this["AnaArchivesDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\ROLLUP-PILOT\\ANAQ\\Invalid")]
        public string AnaErrorDirectory {
            get {
                return ((string)(this["AnaErrorDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\DUCH")]
        public string DucSourceDirectory {
            get {
                return ((string)(this["DucSourceDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\DUCH\\Archive")]
        public string DucArchivesDirectory {
            get {
                return ((string)(this["DucArchivesDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\DUCH\\Invalid")]
        public string DucErrorDirectory {
            get {
                return ((string)(this["DucErrorDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\ROLLUP-PILOT\\EVEQ")]
        public string EveSourceDirectory {
            get {
                return ((string)(this["EveSourceDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\ROLLUP-PILOT\\EVEQ\\Archive")]
        public string EveArchivesDirectory {
            get {
                return ((string)(this["EveArchivesDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\ROLLUP-PILOT\\EVEQ\\Invalid")]
        public string EveErrorDirectory {
            get {
                return ((string)(this["EveErrorDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\ROLLUP-PILOT\\SACQ")]
        public string SacSourceDirectory {
            get {
                return ((string)(this["SacSourceDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\ROLLUP-PILOT\\SACQ\\Archive")]
        public string SacArchivesDirectory {
            get {
                return ((string)(this["SacArchivesDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\ROLLUP-PILOT\\SACQ\\Invalid")]
        public string SacErrorDirectory {
            get {
                return ((string)(this["SacErrorDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\ROLLUP-PILOT\\ANAQ\\InProcess")]
        public string AnaInProcessDirectory {
            get {
                return ((string)(this["AnaInProcessDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.18\\ZCam\\DUCH\\InProcess")]
        public string DucInProcessDirectory {
            get {
                return ((string)(this["DucInProcessDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\ROLLUP-PILOT\\EVEQ\\InProcess")]
        public string EveInProcessDirectory {
            get {
                return ((string)(this["EveInProcessDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\ROLLUP-PILOT\\SACQ\\InProcess")]
        public string SacInProcessDirectory {
            get {
                return ((string)(this["SacInProcessDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("net.tcp://OMSVEPIAZU902/E10Pilot")]
        public string AppServerUrl {
            get {
                return ((string)(this["AppServerUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.1.2.30\\Epicor\\ZCam\\ROLLUP-PILOT\\Quotes")]
        public string LoadPath {
            get {
                return ((string)(this["LoadPath"]));
            }
        }
    }
}
